# ===================================
#  Relation Behavior Config
# ===================================

taxes:
    label: 'winter.mall::lang.common.taxes'
    view:
        list: $/winter/mall/models/tax/columns.yaml
        toolbarButtons: add|create|remove
    manage:
        form: $/winter/mall/models/tax/fields.yaml
        recordsPerPage: 10
    deferredBinding: true