matrix:
  allow_failures:
    - php: nightly
  include:
    - language: php
      services:
        - mysql
      php:
        - 7.2
        - 7.3
        - 7.4
        - 8.0
      sudo: false
      before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS winter;'
      install:
        - composer self-update
        - git clone https://github.com/wintercms/winter.git
        - mkdir -p ./winter/plugins/winter/mall
        - cd winter
        - git checkout 1.0
        - travis_retry composer install --no-interaction --prefer-source
        - php artisan winter:env
        - php artisan key:generate
        - echo "DB_HOST=127.0.0.1" > .env
        - echo "DB_DATABASE=winter" >> .env
        - echo "DB_USERNAME=root" >> .env
        - echo "DB_PASSWORD=" >> .env
        - php artisan winter:up -v
        - php artisan plugin:install Winter.Translate
        - php artisan plugin:install Winter.User
        - php artisan plugin:install Winter.Location
        - cd ..
      before_script:
        - mv !(winter) winter/plugins/winter/mall
        - cd winter
        - php artisan winter:up -v
        - cd plugins/winter/mall
        - travis_retry composer require illuminate/support ^5.5 # force Laravel 5.5 dependencies
        - travis_retry composer install --no-interaction --prefer-source
      script: ../../../vendor/bin/phpunit

    - language: node_js
      node_js:
        - "10"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      install:
        - npm install -g vuepress
      script:
        - cd docs
        - vuepress build
      cache:
        directories:
          - "node_modules"
        notifications:
          email: false
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN
        repo: wintercms/wn-mall-plugin
        keep-history: false
        target-branch: gh-pages
        on:
          branch: develop
