name: Brands
modelClass: Winter\Mall\Models\Brand
form: $/winter/mall/models/brand/fields.yaml
defaultRedirect: winter/mall/brands
create:
    title: 'winter.mall::lang.titles.brands.create'
    redirect: 'winter/mall/brands/update/:id'
    redirectClose: winter/mall/brands
update:
    title: 'winter.mall::lang.titles.brands.edit'
    redirect: winter/mall/brands
    redirectClose: winter/mall/brands
preview: {  }
