name: 'winter.mall::lang.common.notifications'
modelClass: Winter\Mall\Models\Notification
form: $/winter/mall/models/notification/fields.yaml
defaultRedirect: winter/mall/notifications
create:
    title: 'winter.mall::lang.titles.notifications.create'
    redirect: 'winter/mall/notifications/update/:id'
    redirectClose: winter/mall/notifications
update:
    title: 'winter.mall::lang.titles.notifications.update'
    redirect: winter/mall/notifications
    redirectClose: winter/mall/notifications
