title: 'winter.mall::lang.common.addresses'
modelClass: Winter\Mall\Models\Address
list: $/winter/mall/models/address/columns.yaml
recordUrl: 'winter/mall/addresses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
