title: 'winter.mall::lang.common.payments'
modelClass: Winter\Mall\Models\PaymentLog
list: $/winter/mall/models/paymentlog/columns.yaml
recordUrl: 'winter/mall/paymentlogs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
filter: config_filter.yaml
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
