dataSource: client
keyFrom: id
recordsPerPage: false
adding: false
deleting: false
searching: false
alias: pricetable
columns:
    name:
        title: winter.mall::lang.common.product_or_variant
        readOnly: true
    stock:
        title: winter.mall::lang.product.stock
    price:
        title: winter.mall::lang.product.price
