# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    category:
        label: winter.mall::lang.common.category
        modelClass: Winter\Mall\Models\Category
        scope: inCategories

    created_at:
        label: winter.mall::lang.common.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    published:
        label: winter.mall::lang.common.hide_published
        type: checkbox
        conditions: published <> true

    is_virtual:
        label: winter.mall::lang.product.filter_virtual
        type: checkbox
        conditions: is_virtual = true