# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: 'winter.mall::lang.common.property'
    deferredBinding: false
    showSorting: false
    view:
        list: $/winter/mall/models/property/columns_pivot.yaml
        toolbarButtons: add|create|remove
        defaultSort:
            column: pivot[sort_order]
            direction: asc
    manage:
        form: $/winter/mall/models/property/fields_pivot.yaml
        list: $/winter/mall/models/property/columns.yaml
        showSearch: true
        recordsPerPage: 50
    pivot:
        form: $/winter/mall/models/property/fields_pivot.yaml
