title: 'winter.mall::lang.common.discounts'
modelClass: Winter\Mall\Models\Discount
list: $/winter/mall/models/discount/columns.yaml
recordUrl: 'winter/mall/discounts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
