title: 'winter.mall::lang.common.customer_groups'
modelClass: Winter\Mall\Models\CustomerGroup
list: $/winter/mall/models/customergroup/columns.yaml
recordUrl: 'winter/mall/customergroups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
