title: 'winter.mall::lang.common.orders'
modelClass: Winter\Mall\Models\Order
list: $/winter/mall/models/order/columns.yaml
recordUrl: 'winter/mall/orders/show/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: false
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
