options:
    label: 'winter.mall::lang.services.option'
    view:
        list: $/winter/mall/models/serviceoption/columns.yaml
        toolbarButtons: create|delete
        defaultSort: ['sort_order',  'ASC']
    manage:
        form: $/winter/mall/models/serviceoption/fields.yaml
        recordsPerPage: 10

products:
    label: 'winter.mall::lang.common.products'
    view:
        showSearch: true
        list: $/winter/mall/models/product/columns.yaml
        toolbarButtons: add|remove
        recordUrl: 'winter/mall/products/update/:id'
    pivot:
        form: $/winter/mall/models/service/fields_pivot.yaml


taxes:
    label: 'winter.mall::lang.common.taxes'
    view:
        list: $/winter/mall/models/tax/columns.yaml
        toolbarButtons: add|create|remove
    manage:
        form: $/winter/mall/models/tax/fields.yaml
        recordsPerPage: 10
    deferredBinding: true