title: 'winter.mall::lang.common.taxes'
modelClass: Winter\Mall\Models\Tax
list: $/winter/mall/models/tax/columns.yaml
recordUrl: 'winter/mall/taxes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
