name: 'winter.mall::lang.common.reviews'
modelClass: Winter\Mall\Models\Review
form: $/winter/mall/models/review/fields.yaml
defaultRedirect: winter/mall/reviews
create:
    title: 'winter.mall::lang.titles.reviews.create'
    redirect: 'winter/mall/reviews/update/:id'
    redirectClose: winter/mall/reviews
update:
    title: 'winter.mall::lang.titles.reviews.update'
    redirect: winter/mall/reviews
    redirectClose: winter/mall/reviews
preview: {  }
