# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    status:
        label: winter.mall::lang.reviews.only_unapproved
        type: checkbox
        conditions: approved_at is null
