title: 'winter.mall::lang.common.reviews'
modelClass: Winter\Mall\Models\Review
list: $/winter/mall/models/review/columns.yaml
recordUrl: 'winter/mall/reviews/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: approved_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
