title: 'winter.mall::lang.common.variants'
modelClass: Winter\Mall\Models\Variant
list: $/winter/mall/models/variant/columns.yaml
recordUrl: 'winter/mall/variants/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
